[libraries]
adventure-api = { module = "net.kyori:adventure-api", version = "4.17.0" }
creative-api = { module = "team.unnamed:creative-api", version = "1.7.2" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.17.1" }
nexus-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.29.0" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.25.0" }
